title: Jixiang's Blog
# 我亦無他 惟手熟爾
# Big Picture, Big Idea
# Passion and Perseverance
# Stay Hungry Stay Foolish
author: Jixiang Zhang
email: zhangjixiang1995@qq.com
description: Autonomy Engineer
url: "https://matheecs.tech/"
favicon: "./favicon.ico"

# Build settings
# theme: moving
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Big Picture, Big Idea
  avatar_url: https://tva4.sinaimg.cn/large/d494c514ly1gcj6lwgm0hj22042ca7wh.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github: matheecs
    linkedin: matheecs-tech