# Site settings
# 我亦無他 惟手熟爾
# Big Picture, Big Idea
title: Passion and Perseverance
email: matheecs@stu.xjtu.edu.cn
description: Engineering, Sketching and Mathematics
baseurl: "/"
url: "https://matheecs.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM