title: Jixiang's Blog
# 我亦無他 惟手熟爾
# Big Picture, Big Idea
# Passion and Perseverance
# Stay Hungry Stay Foolish
# zhangjixiang1995@qq.com
author: Jixiang Zhang (matheecs)
email: matheecs@qq.com
description: Autonomy Engineer
url: "https://matheecs.tech"
favicon: "./favicon.ico"

# Build settings
# theme: moving
remote_theme: matheecs/moving
plugins:
  - jekyll-feed

moving:
  about_you: Big Picture, Big Idea
  avatar_url: https://tva1.sinaimg.cn/large/d494c514ly1gcmbadww41j2204201nk4.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    # rss: RSS
    github: matheecs
    linkedin: matheecs-tech
    bilibili: '395348622'