title: Jixiang's Notebook
# 我亦無他 惟手熟爾
# Big Picture, Big Idea
# Passion and Perseverance
# Stay Hungry Stay Foolish
# Echo & Convex Hull
# I design and make robots.
# MPC=Mapping+Planning+Control
# to learn, READ. to know, WRITE. to master, TEACH.
# I Make Quadruped and Quadcopter Robot.
# 机器人或许是真实世界里的游戏
# What I cannot create, I do not understand
author: Jixiang Zhang (matheecs)
email: matheecs[at]qq[dot]com
description: If you can't explain it simply, you don't understand it well enough.
url: "https://matheecs.tech"
favicon: "favicon.ico"

# Build settings
# theme: moving
remote_theme: matheecs/moving
plugins:
  - jekyll-feed

moving:
  about_you: Big Picture, Big Idea
  avatar_url: https://tva1.sinaimg.cn/large/d494c514ly1gcmbadww41j2204201nk4.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    # rss: RSS
    github: matheecs
    # linkedin: matheecs-tech
    bilibili: "395348622"
